export const ROUTES = {
  landing: "/",
  login: "/login",
  citizenLogin: "/citizen-login",
  signup: "/signup",
  otp: "/otp",
  citizen: "/citizen",
  citizenCreateComplaint: "/citizen/create-complaint",
  citizenComplaintList: "/citizen/complaints",
  citizenComplaintDetails: "/citizen/complaints/:id",
  field: "/field",
  manager: "/manager",
  rep: "/rep",
  admin: "/admin",
  adminSignup: "/admin-signup",
  register: "/admin/register",
  registerMLA: "/admin/register/mla",
  registerManager: "/admin/register/manager",
  registerFieldOfficer: "/admin/register/field-officer",
  mlaList: "/admin/mla-list",
  citizenList: "/admin/users",
  adminUsers: "/admin/users",
  reports: "/admin/reports",
  settings: "/admin/settings",
};
