export const ROUTES = {
  landing: "/",
  login: "/login",
  citizenLogin: "/citizen-login",
  signup: "/signup",
  otp: "/otp",
  citizen: "/citizen",
  citizenCreateComplaint: "/citizen/create-complaint",
  citizenComplaintList: "/citizen/complaints",
  citizenComplaintDetails: "/citizen/complaints/:id",
  field: "/field",
  manager: "/manager",
  rep: "/rep",
  admin: "/admin",
  adminSignup: "/admin-signup",
  newMLA: "/admin/new-mla",
  newManager: "/admin/new-manager",
  newFieldOfficer: "/admin/new-field-officer",
  mlaList: "/admin/mla-list",
  adminUsers: "/admin/users",
};